@baseUrl = http://localhost:5099/api/films

### Get all films
GET {{baseUrl}}/

### Get films by title
GET {{baseUrl}}/?title=My Neighbor Totoro

### Get film by ID
GET {{baseUrl}}/b8868098-8d2d-4168-8286-eb3979b304d5


### Update film
PUT {{baseUrl}}/b8868098-8d2d-4168-8286-eb3979b304d5
Content-Type: application/json

{
  "id": "b8868098-8d2d-4168-8286-eb3979b304d5",
  "title": "Nausicaä of the Valley of the Wind",
  "originalTitle": "風の谷のナウシカ",
  "originalTitleRomanised": "Kaze no Tani no Nausicaä",
  "image": "https://image.tmdb.org/t/p/w600_and_h900_bestv2/tcrkfB8SRPQCgwI88hQScua6nxh.jpg",
  "movieBanner": "https://image.tmdb.org/t/p/original/ulVUa2MvnJAjAeRt7h23FFJVRKH.jpg",
  "description": "After a global war, the seaside kingdom known as the Valley of the Wind remains one of the last strongholds on Earth untouched by a poisonous jungle and the powerful insects that guard it. Led by the courageous Princess Nausicaä, the people of the Valley engage in an epic struggle to restore the bond between humanity and Earth.",
  "director": "Hayao Miyazaki",
  "producer": "Isao Takahata",
  "releaseDate": 1984,
  "runningTime": 117,
  "rtScore": 91
}
