// <auto-generated />
using ConvertJsonToSqlite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConvertJsonToSqlite.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ConvertJsonToSqlite.Models.Domain.Film", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieBanner")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitleRomanised")
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RtScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunningTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("ConvertJsonToSqlite.Models.Domain.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Climate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurfaceWater")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terrain")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ConvertJsonToSqlite.Models.Domain.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .HasColumnType("TEXT");

                    b.Property<string>("EyeColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HairColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeciesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ConvertJsonToSqlite.Models.Domain.Species", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<string>("EyeColors")
                        .HasColumnType("TEXT");

                    b.Property<string>("HairColors")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("ConvertJsonToSqlite.Models.Domain.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Length")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleClass")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PilotId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("FilmLocation", b =>
                {
                    b.Property<string>("FilmsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationsId")
                        .HasColumnType("TEXT");

                    b.HasKey("FilmsId", "LocationsId");

                    b.HasIndex("LocationsId");

                    b.ToTable("FilmLocation");
                });

            modelBuilder.Entity("FilmPerson", b =>
                {
                    b.Property<string>("FilmsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeopleId")
                        .HasColumnType("TEXT");

                    b.HasKey("FilmsId", "PeopleId");

                    b.HasIndex("PeopleId");

                    b.ToTable("FilmPerson");
                });

            modelBuilder.Entity("FilmSpecies", b =>
                {
                    b.Property<string>("FilmsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeciesId")
                        .HasColumnType("TEXT");

                    b.HasKey("FilmsId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("FilmSpecies");
                });

            modelBuilder.Entity("FilmVehicle", b =>
                {
                    b.Property<string>("FilmsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehiclesId")
                        .HasColumnType("TEXT");

                    b.HasKey("FilmsId", "VehiclesId");

                    b.HasIndex("VehiclesId");

                    b.ToTable("FilmVehicle");
                });

            modelBuilder.Entity("ConvertJsonToSqlite.Models.Domain.Person", b =>
                {
                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Location", null)
                        .WithMany("Residents")
                        .HasForeignKey("LocationId");

                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Species", "Species")
                        .WithMany("People")
                        .HasForeignKey("SpeciesId");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ConvertJsonToSqlite.Models.Domain.Vehicle", b =>
                {
                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Person", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("FilmLocation", b =>
                {
                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmPerson", b =>
                {
                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmSpecies", b =>
                {
                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmVehicle", b =>
                {
                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConvertJsonToSqlite.Models.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehiclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConvertJsonToSqlite.Models.Domain.Location", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("ConvertJsonToSqlite.Models.Domain.Species", b =>
                {
                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
